#!/bin/bash

status=$(expressvpn status)
if [[ "$status" == *"Not connected."* ]]; then
  connected=false
else
  connected=true
fi

case $BLOCK_BUTTON in
  1) if $connected ; then expressvpn disconnect > /dev/null; else expressvpn connect > /dev/null; fi ;;
esac

if $connected ; then
  ip=$(expressvpn diagnostics | egrep ".*ip.*protocol.*" | grep --color=never -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')
  loc=$(echo $status | rev | cut -f1 -d' ' | rev)
  echo "$loc <span color='#00FF00'>$ip</span>"
else
  echo "<span color='#FF0000'>vpn down</span>"
fi
